remove support for making the player starve
Related to this crash:

Caused by: java.lang.NoSuchMethodError: net.minecraft.util.FoodStats.func_75119_b(F)V
    at love.marblegate.flowingagony.util.PlayerUtil.crazilyComsumeFoodLevel(PlayerUtil.java:102) ~[flowingagony:1.16.5-beta-0.2.0] {re:classloading}
    at love.marblegate.flowingagony.effect.ExtremeHatredEffect.func_76394_a(ExtremeHatredEffect.java:18) ~[flowingagony:1.16.5-beta-0.2.0] {re:classloading}

Mappings will have to be updated for a full fix, I think